### ISSUE TITLE
Can't get json output for all namespace

### ISSUE THREAD

**Issue by timzhang926** [kei6u/kubectl-secret-data#7]
Hi there,

I've installed the secretdata successfully. However, when I run the first command, it failed. Could you please have a look? Thank you.

```
kubectl secretdata -A -o json
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.getSecretData({0x1aceb70, 0xc0001beac0})
        /home/runner/work/kubectl-secretdata/kubectl-secretdata/options.go:216 +0x368
main.(*Options).Run(0xc0002420c0, {0x1b19d40, 0xc00069cd00})
        /home/runner/work/kubectl-secretdata/kubectl-secretdata/options.go:169 +0xf6
main.NewCmd.func1(0xc000344500, {0xc000705170, 0x3, 0x3})
        /home/runner/work/kubectl-secretdata/kubectl-secretdata/options.go:70 +0x68
github.com/spf13/cobra.(*Command).execute(0xc000344500, {0xc000138050, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000344500)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /home/runner/work/kubectl-secretdata/kubectl-secretdata/main.go:9 +0x1e
```

**Comment by keisku** [comment]
@zhangxd926 
Thank you for reporting bug!
I fixed this bug by https://github.com/kei6u/kubectl-secretdata/pull/8.
Please try this version. https://github.com/kei6u/kubectl-secretdata/releases/tag/v1.0.2

**Comment by timzhang926** [comment]
Really appreciate your prompt reply. It works well with v1.0.2 and I like your json layout which is very concise.
At the same time, I tried to use jq to format the secret, maybe you're interested in it as well.
```
kubectl get secret --all-namespaces -o json | jq '[.items[] | {"namespace":.metadata.namespace, "secret":.metadata.name, "data":.data | values | to_entries | map({"key":.key,"value":.value | @base64d}) | from_entries}]'
```
